### ISSUE TITLE
Problems: table is not sortable

### ISSUE THREAD

**Issue by Shloub** [jilljenn/tryalgo#13]
It seems the `<table>` generated from MD does not include class="sortable".

**Comment by jilljenn** [comment]
Yes indeed, actually we should directly generate HTML so we could add the class… Thanks!

**Comment by xtof-durr** [comment]
le script yaml2html.py fait exactement ça.
Tu as vu pour l’instant sur amazon on est vente #1 dans la catégorie programmation (40.000 titres). Mais c’est normal pour une sortie, on va voir dans 2 semaines si on garde cette place.
Christoph

**Comment by xtof-durr** [comment]
… ça y est aujourd’hui on est plus en top de vente sur amazon.

**Comment by xtof-durr** [comment]
done
