### ISSUE TITLE
cut_nodes_edges2 not in tryalgo-1.0

### ISSUE THREAD

**Issue by jyloup** [jilljenn/tryalgo#14]
When installing tryalgo with pip command (using internet connection), cut_nodes_edges2 is not in source code, so tryalgo test script makes an error.

**Comment by xtof-durr** [comment]
I suspect that you run the test script orginating from the latest github version with the tryalgo library from the pypi repository.
There will be no error if you run the test script from github on the library from github or of you run the test script from pypi on the library from pypi.
We will make a tryalgo-1.1 version on pypi from the current github version these days.
