### ISSUE TITLE
anagrams modifies its input

### ISSUE THREAD

**Issue by Shloub** [jilljenn/tryalgo#15]
Is there a specific reason for this? This side-effect feels unnatural to me. Maybe another name could be used instead of w? `unique_w = list(set(w))`?

Edit: It seems anagrams actually doesn't modify its input, my bad.

**Comment by xtof-durr** [comment]
Hmm, yes it would be better style to keep the parameters as they are given. In fact replacing the first line by

      assert len(w) == len(set(w))

could be a better choice.
