### ISSUE TITLE
tests: sorted instead of set in unorder?

### ISSUE THREAD

**Issue by Shloub** [jilljenn/tryalgo#17]
I think sorted instead of set/frozenset could ensure tests a bit stricter/safer (just in case anagrams doesn't return unique objects).

**Comment by xtof-durr** [comment]
oui mais avec sorted(w) on n’a pas enlevé les doublons, et la complexité est plus grande (nlogn au lieu de n — sous hypothèse que les fonctions de hashage soient sans trop de collisions)

**Comment by Shloub** [comment]
@xtof-durr Pour être bien clair : je parle du fichier de test https://github.com/jilljenn/tryalgo/blob/master/tests/test_tryalgo.py#L90

Je ne sais pas si la complexité est très importante ici, mais je pense que justement, un test plus strict permet éventuellement de repérer plus d'erreurs dans le code testé (même si ici, je doute en effet qu'anagrams ait ce problème).

**Comment by xtof-durr** [comment]
C'est une superbe idée, je viens de changer order pour qu'elle utilise ordered.
Pour les tests la complexité n'est pas trop importante.
