### ISSUE TITLE
arithm_expr_eval.py doc: line parameter for arithm_expr_parse is not a string

### ISSUE THREAD

**Issue by Shloub** [jilljenn/tryalgo#18]
The doc reads « :param line: string containing the expression », although, it seems the expected parameter is a list of strings.

https://github.com/jilljenn/tryalgo/blob/master/tryalgo/arithm_expr_eval.py#L48

Example: `tryalgo.arithm_expr_eval.arithm_expr_parse(["3", "+", "1"])`

**Comment by xtof-durr** [comment]
Bien vu, merci
