### ISSUE TITLE
Typo in a link in the doc

### ISSUE THREAD

**Issue by Naereen** [jilljenn/tryalgo#42]
https://github.com/jilljenn/tryalgo/blob/2b7ae92549e41aa83c4cf8eb481523f74afe2566/docs/content.rst#L27

this links does not render nicely. See [the end of this paragraph](https://pythonhosted.org/tryalgo/content.html#basic-algorithms-and-data-structures):
![typo in link](https://user-images.githubusercontent.com/11994719/38020477-9e31a06c-327a-11e8-879d-eeca49e0f8e2.png)

**Comment by Naereen** [comment]
Anyone? @jilljenn ?

**Comment by jilljenn** [comment]
Christoph did! https://github.com/jilljenn/tryalgo/commit/d11a60da1b5bc05ee37fad9102af4ae7abbbb6f0

**Comment by Naereen** [comment]
OK

**Comment by jilljenn** [comment]
So yes indeed, we have two versions of the docs.
- https://pythonhosted.org/tryalgo/
- http://jilljenn.github.io/tryalgo/
Both are not updated yet.

**Comment by jilljenn** [comment]
https://jilljenn.github.io/tryalgo/ was rebuilt with Read the Docs theme! Enjoy!

**Comment by xtof-durr** [comment]
joli doc. Super ce thème.
On ne garde que https://jilljenn.github.io/tryalgo/ <https://jilljenn.github.io/tryalgo/> d'accord. 
Ça ne sert à rien d'avoir 
https://pythonhosted.org/tryalgo/ <https://pythonhosted.org/tryalgo/>
aussi.
Je regarde les liens vers la doc, et quand tout est corrigé, je supprime pythonhosted.

xtof

**Comment by Naereen** [comment]
- The new theme is fine (i was saying so for years!), thanks @jilljenn to have updated it.
- I agree with @xtof-durr it's not mandatory to have the doc in two different websites. (I'm ashamed to still have the doc of my [SMPyBandits](https://smpybandits.github.io/) project on four different websites!)
- @xtof-durr maybe don't delete entirely the website on https://pythonhosted.org/tryalgo/ : you could instead upload one last time a zip archive, containing a simple HTML page that redirects to the other one? Here is an example:
```html
<html>
    <head>
        <meta HTTP-EQUIV="REFRESH" content="0; url=https://jilljenn.github.io/tryalgo/">
    </head>
    <body>
        Redirecting to <a href="https://jilljenn.github.io/tryalgo/">https://jilljenn.github.io/tryalgo/</a>...
    </body>
</html>
```

**Comment by Naereen** [comment]
(It works without javascript!)

**Comment by xtof-durr** [comment]
Bonsoir,

j'ai fait une version tryalgo 1.3 sur pypi.
J'ai enlevé tous les liens que j'ai pu voir vers pythonhosted.
J'ai vu que je ne peux plus changer la doc, ni même mettre une page de redirection.
Je pense qu'après une nuit reposé, je serais prêt à cliquer sur le grand bouton rouge.

xtof
