### ISSUE TITLE
I think we need the list of 128 algorithms on the README

### ISSUE THREAD

**Issue by jilljenn** [jilljenn/tryalgo#49]
Should be generated. I remember @xtof-durr you made a script for that!

**Comment by xtof-durr** [comment]
(4 de plus pour le même prix)

1. $s-t$ Coupe minimum planaire
2. $s-t$ Coupe minimum
3. 2-satisfiabilité
4. Ancêtre commun le plus proche par minimum dans une plage
5. Ancêtre commun le plus proche par racourcis
6. Andrew : convex hull
7. Andrew : enveloppe convexe
8. Arêtes critiques pour plus court chemin
9. Bellman-Ford var. : cycle poids négatif
10. Bellman-Ford : plus court chemin poids arbitraires
11. Chemin minimisant arête poids maximal
12. Chemin minimisant sommet poids maximal
13. Code de Huffman
14. Coefficient binomial direct
15. Coefficient binomial par coefficients de Bézout
16. Coefficient binomial par programmation dynamique
17. Coefficients de Bézout
18. Combiner $n$ entiers en une expression arithmétique de valeur proche d'une valeur donnée
19. Composantes bi-connexes d'un graphe
20. Composantes connexes d'un graphe avec union-find
21. Composantes connexes d'un graphe par parcours en profondeur
22. Composants dans union de rectangles disjoints
23. Correcteur orthographique
24. Coupe minimum dans arbre pour minimiser plus long chemin
25. Couplage biparti maximal en $O(|U|\cdot|E|)$
26. Couplage biparti parfait minimisant arête poids maximal
27. Couplage planaire en $O(n\log n)$
28. Couplage planaire par en $O(n^3)$
29. Cycle de coût sur temps minimal
30. Cycle de poids moyen minimal
31. Cycle eulérien
32. Dijkstra : plus court chemin poids positifs ou nuls
33. Dinic : flot maximum par flot bloquant
34. Distance d'édition de Levenshtein entre deux chaînes
35. Décomposition minimale en chaînes d'un ordre partiel
36. Déterminer toutes les sous-séquences maximales composées d'éléments distincts
37. Edmonds-Karp : flot maximum par chemin augmentant plus court
38. Ensemble minimum de points intersectant chacun des intervalles donnés
39. Exponentiation rapide
40. Fenwick : tableau avec écriture par indice et lecture somme sur intervalle d'indices
41. Floyd-Warshall : plus courts chemins toutes paires source-destination
42. Ford-Fulkerson : flot maximum par chemins augmentants
43. Fusionner $k$ listes triées
44. Fusionner deux listes triées
45. Gale-Shapley : couplage biparti stable
46. Gauss-Jordan : système d'équations linéaires
47. Goldberg-Rao : flot maximum par flots bloquants binaires
48. Gries-Misra : nombres premiers
49. Intervalle dans tableau de somme maximale
50. Inverser une fonction monotone
51. Knuth-Morris-Pratt : bord maximal d'une chaîne
52. Knuth-Morris-Pratt : recherche d'une sous-chaîne
53. Kosaraju : composantes fortement connexes
54. Kruskal : arbre couvrant de poids minimal
55. Kuhn-Munkres : couplage biparti maximum profit maximal
56. Kőnig : couverture minimale par sommets d'un graphe biparti
57. Liens dansants : couverture exacte
58. Maintenir ensemble d'intervalles, déterminer liste d'intervalles contenant une valeur donnée
59. Manacher : plus long facteur palindrome
60. Nombres de Fibonacci
61. Orienter miroirs pour connectivité laser
62. Paire de points plus proches
63. Paire de valeurs plus proches
64. Parcours d'un graphe en largeur
65. Parcours d'un graphe en profondeur
66. Partition d'un ensemble d'entiers en deux parties
67. Partition d'un ensemble d'entiers en trois parties
68. Permuter vecteur $x$ pour minimiser le produit scalaire avec $y$
69. Placer des parenthèses pour optimiser une multiplication d'une séquence de matrices
70. Plus court chemin avec poids 0,1
71. Plus court chemin dans grille
72. Plus court chemin dans une grille
73. Plus court chemin graphe orienté acyclique
74. Plus court chemin sur graphe de configurations combinatoires
75. Plus grand carré monochromatique dans une grille
76. Plus grand commun diviseur
77. Plus grand rectangle dans histogramme
78. Plus grand rectangle monochromatique dans un grille
79. Plus long chemin dans un arbre par parcours en profondeur
80. Plus long chemin dans un arbre par programmation dynamique
81. Plus longue sous-séquence commune et croissante à deux séquences
82. Plus longue sous-séquence commune à $k$ séquences données
83. Plus longue sous-séquence commune à deux séquences triées
84. Plus longue sous-séquence commune à deux séquences
85. Plus longue sous-séquence non décroissante
86. Plus longue sous-séquence strictement croissante
87. Points entiers dans un polygone
88. Points entiers sur le contour d'un polygone
89. Postier chinois : cycle minimal couvrant chaque arête
90. Pour une chaîne $x$ trouver un entier $k$ tel que $x$ s'écrit comme $y^k$ pour une chaîne $y$
91. Prim : arbre couvrant de poids minimal
92. Problème de transport
93. Prochaine permutation
94. Proposer le mot le plus fréquent correspondant à un préfixe donné en mode T9
95. Rabin-Karp : chercher plus long facteur commun à deux chaînes en temps $O(n\log n)$
96. Rabin-Karp : chercher une chaîne dans une autre
97. Recherche dichotomique dans un domaine continu
98. Recherche dichotomique dans un tableau de taille $2^k$
99. Recherche dichotomique dans un tableau trié
100. Recherche trichotomique pour trouver le minimum d'une séquence convexe
101. Rendu de monnaie
102. Sac-à-dos
103. Simplicité polygone rectilinéaire
104. Somme d'un tableau sur un intervalle d'indices
105. Sous-ensemble de valeur totale donnée par intersection d'ensembles
106. Sous-ensemble de valeur totale donnée par programmation dynamique
107. Sous-matrice rectangulaire de somme maximale
108. Stratégie gagnante dans un jeu
109. Sudoku
110. Surface d'un polygone
111. Tableau avec écriture par indice et lecture minimum sur intervalle d'indices
112. Tarjan : composantes fortement connexes
113. Tas
114. Temps de déconnexion d'un graphe avec heure disparition par arête
115. Test probabiliste de Freivalds $AB=C$
116. Tous les rectangles formés par des points donnés
117. Tri casier
118. Trouver toutes les anagrammes à une liste de mots
119. Union d'intervalles
120. Union de rectangles en $O(n\log n)$
121. Union de rectangles en $O(n^2)$
122. Union de rectangles en $O(n^4)$
123. Union-find
124. Valeur intersectant un nombre maximal d'intervalles
125. Voyageur de commerce
126. couverture minimale par arêtes d'un graphe biparti
127. k-somme en $O(n^{\lceil k/2 \rceil})$
128. k-somme en $O(n^{k-1})$
129. Élément en double d'un tableau sur un intervalle d'indices
130. Élément majoritaire d'un tableau
131. Ératosthène : nombres premiers
132. Évaluer une expression arithmétique
