### ISSUE TITLE
anagrams.py input ?

### ISSUE THREAD

**Issue by remic33** [jilljenn/tryalgo#54]
In the book you talk about an input : 
'le chien marche vers sa niche et trouve une limace de chine nue pleine de malice qui lui fait du charme'
A string, but in your code you talk about a list. 
In both cases, you cant turn a set into a list using list(set(w)) it give TypeError: 'set' object is not subscriptable
Am I missing something?

**Comment by jilljenn** [comment]
Indeed, it requires a list of words, just like [in the tests](https://github.com/jilljenn/tryalgo/blob/master/tests/test_tryalgo.py#L101) (see the `split()`).

`list(set(w))` removes the duplicates of this list. What version of Python are you using?

    Python 3.7.5rc1 (default, Oct  8 2019, 16:47:45) 
    [GCC 9.2.1 20191008] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> w = "je répète ce que je dis".split()
    >>> set(w)
    {'que', 'dis', 'répète', 'je', 'ce'}
    >>> list(set(w))
    ['que', 'dis', 'répète', 'je', 'ce']

**Comment by xtof-durr** [comment]
Yes, we should have been more clear that this function takes a list as
argument. The variable name "w" suggests that it is a word.

We already mentioned it here:
https://tryalgo.org/errata/

**Comment by xtof-durr** [comment]
We modified the code to improve readability. Now it should be clear how to use this function.
