### ISSUE TITLE
Data Input Format for Gale-Shapley

### ISSUE THREAD

**Issue by kalee** [jilljenn/tryalgo#67]
How would you format the data for the SPOC example data, specifically the two 4x4 data sets.
women
4 3 1 2
2 1 3 4
1 3 4 2
4 3 1 2
men
3 2 4 1
2 3 1 4
3 1 2 4
3 2 4 1

I tried:
women = [[4,3,1,2],[2,1,3,4],[1,3,4,2],[4,3,1,2]]
men = [[3,2,4,1],[2,3,1,4],[3,1,2,4],[3,2,4,1]]

spouse = gale_shapley(men, women)
print(spouse)

When I call the function, I get the following error message.
[<ipython-input-4-ab0b756c6a16>](https://localhost:8080/#) in <module>
     61 #men.append([3,2,4,1])
     62 
---> 63 spouse = gale_shapley(men, women)
     64 print(spouse)

[<ipython-input-4-ab0b756c6a16>](https://localhost:8080/#) in gale_shapley(men, women)
     20     for r in range(n):
     21       print(j,r,women[j][r])
---> 22       rank[j][women[j][r]] = r
     23   singles = deque(range(n))  # all men are single and get in the queue
     24   while singles:

IndexError: list assignment index out of range

I did try modifying the data so that it is zero based, but you still get an error.  The data in the problem is generally like what was given above.

Any help appreciated!

**Comment by xtof-durr** [comment]
Dear Kenneth Lee, 
you put the finger on an implementation error that was sleeping for long time. It happens that we used a FIFO queue to store the unmarried men, and did not use this data structure correctly. We corrected the code and use a stack which is simpler. We apologize. And indeed, the men/women identifier should be given 0-based.

>>> gale_shapley([[1,0,3,2],[2,1,0,3],[1,3,2,0],[3,1,0,2]], [[2,1,3,0],[3,1,0,2],[0,2,1,3],[0,3,2,1]])
[0, 1, 2, 3]
